version: '3.7'

services:
  octoprint:
    image: octoprint/octoprint
    ports:
      - 4000:5000
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - octoprint:/home/octoprint

volumes:
  octoprint:
